name: CI

on:
  push:
    branches:
      - master
      - cicd-test
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"
  pull_request:

env:
  GO_VERSION: 1.22
  GOFLAGS: -mod=readonly

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          # Required for correctly populating ldflags
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binaries and libraries
        run: make build

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run unit tests
        run: make test

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up test environment
        run: make up

      - name: Run integration tests
        run: make test-integration
